spring.application.name=do-do-app
spring.jpa.show-sql=true

# Persistent, embedded H2 database. Data is stored in ./data/todo-db.mv.db.
spring.datasource.url=jdbc:h2:file:./data/todo-db
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# JPA/Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Development database console: http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.thymeleaf.cache=false
